spring:
  datasource:
    url: "jdbc:mysql://localhost:3355/cabinet_medical?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
